local lspkind = vim.lsp.protocol.CompletionItemKind

return {
	render_mode = {
		{ label = "blend_mix", kind = lspkind.Module },
		{ label = "blend_add", kind = lspkind.Module },
		{ label = "blend_sub", kind = lspkind.Module },
		{ label = "blend_mul", kind = lspkind.Module },
		{ label = "blend_premul_alpha", kind = lspkind.Module },
		{ label = "blend_disabled", kind = lspkind.Module },
		{ label = "unshaded", kind = lspkind.Module },
		{ label = "light_only", kind = lspkind.Module },
		{ label = "skip_vertex_transform", kind = lspkind.Module },
	},
	vertex_in = {
		{ label = "MODEL_MATRIX", kind = lspkind.Constant },
		{ label = "CANVAS_MATRIX", kind = lspkind.Constant },
		{ label = "SCREEN_MATRIX", kind = lspkind.Constant },
		{ label = "INSTANCE_CUSTOM", kind = lspkind.Constant },
		{ label = "AT_LIGHT_PASS", kind = lspkind.Constant },
		{ label = "TEXTURE_PIXEL_SIZE", kind = lspkind.Constant },
	},
	vertex_inout = {
		{ label = "VERTEX", kind = lspkind.Property },
		{ label = "UV", kind = lspkind.Property },
		{ label = "COLOR", kind = lspkind.Property },
		{ label = "POINT_SIZE", kind = lspkind.Property },
	},
	fragment_in = {
		{ label = "FRAGCOORD", kind = lspkind.Constant },
		{ label = "SCREEN_PIXEL_SIZE", kind = lspkind.Constant },
		{ label = "POINT_COORD", kind = lspkind.Constant },
		{ label = "TEXTURE", kind = lspkind.Constant },
		{ label = "TEXTURE_PIXEL_SIZE", kind = lspkind.Constant },
		{ label = "AT_LIGHT_PASS", kind = lspkind.Constant },
		{ label = "SPECULAR_SHININESS_TEXTURE", kind = lspkind.Constant },
		{ label = "SPECULAR_SHININESS", kind = lspkind.Constant },
		{ label = "UV", kind = lspkind.Constant },
		{ label = "SCREEN_UV", kind = lspkind.Constant },
	},
	fragment_inout = {
		{ label = "NORMAL", kind = lspkind.Property },
		{ label = "NORMAL_TEXTURE", kind = lspkind.Property },
		{ label = "VERTEX", kind = lspkind.Property },
		{ label = "SHADOW_VERTEX", kind = lspkind.Property },
		{ label = "LIGHT_VERTEX", kind = lspkind.Property },
		{ label = "COLOR", kind = lspkind.Property },
	},
	fragment_out = {
		{ label = "NORMAL_MAP", kind = lspkind.Property },
		{ label = "NORMAL_MAP_DEPTH", kind = lspkind.Property },
	},
	light_in = {
		{ label = "FRAGCOORD", kind = lspkind.Constant },
		{ label = "NORMAL", kind = lspkind.Constant },
		{ label = "COLOR", kind = lspkind.Constant },
		{ label = "UV", kind = lspkind.Constant },
		{ label = "TEXTURE", kind = lspkind.Constant },
		{ label = "TEXTURE_PIXEL_SIZE", kind = lspkind.Constant },
		{ label = "SCREEN_UV", kind = lspkind.Constant },
		{ label = "POINT_COORD", kind = lspkind.Constant },
		{ label = "LIGHT_COLOR", kind = lspkind.Constant },
		{ label = "LIGHT_ENERGY", kind = lspkind.Constant },
		{ label = "LIGHT_POSITION", kind = lspkind.Constant },
		{ label = "LIGHT_DIRECTION", kind = lspkind.Constant },
		{ label = "LIGHT_IS_DIRECTIONAL", kind = lspkind.Constant },
		{ label = "LIGHT_VERTEX", kind = lspkind.Constant },
		{ label = "SPECULAR_SHININESS", kind = lspkind.Constant },
	},
	light_inout = {
		{ label = "LIGHT", kind = lspkind.Property },
	},
	light_out = {
		{ label = "SHADOW_MODULATE", kind = lspkind.Property },
	},
	sdf = { -- fragment and light functions
		{ label = "texture_sdf()", kind = lspkind.Function },
		{ label = "texture_sdf_normal()", kind = lspkind.Function },
		{ label = "sdf_to_screen_uv()", kind = lspkind.Function },
		{ label = "screen_uv_to_sdf()", kind = lspkind.Function },
	},
}
