local lspkind = vim.lsp.protocol.CompletionItemKind

return {
	render_mode = {
		{ label = "blend_mix", kind = lspkind.Module },
		{ label = "blend_add", kind = lspkind.Module },
		{ label = "blend_sub", kind = lspkind.Module },
		{ label = "blend_mul", kind = lspkind.Module },
		{ label = "blend_premul_alpha", kind = lspkind.Module },
		{ label = "depth_draw_opaque", kind = lspkind.Module },
		{ label = "depth_draw_always", kind = lspkind.Module },
		{ label = "depth_draw_never", kind = lspkind.Module },
		{ label = "depth_prepass_alpha", kind = lspkind.Module },
		{ label = "depth_test_disabled", kind = lspkind.Module },
		{ label = "sss_mode_skin", kind = lspkind.Module },
		{ label = "cull_back", kind = lspkind.Module },
		{ label = "cull_front", kind = lspkind.Module },
		{ label = "cull_disabled", kind = lspkind.Module },
		{ label = "unshaded", kind = lspkind.Module },
		{ label = "wireframe", kind = lspkind.Module },
		{ label = "debug_shadow_splits", kind = lspkind.Module },
		{ label = "diffuse_lambert", kind = lspkind.Module },
		{ label = "diffuse_lambert_wrap", kind = lspkind.Module },
		{ label = "diffuse_burley", kind = lspkind.Module },
		{ label = "diffuse_toon", kind = lspkind.Module },
		{ label = "specular_schlick_ggx", kind = lspkind.Module },
		{ label = "specular_toon", kind = lspkind.Module },
		{ label = "specular_disabled", kind = lspkind.Module },
		{ label = "skip_vertex_transform", kind = lspkind.Module },
		{ label = "world_vertex_coords", kind = lspkind.Module },
		{ label = "ensure_correct_normals", kind = lspkind.Module },
		{ label = "shadows_disabled", kind = lspkind.Module },
		{ label = "ambient_light_disabled", kind = lspkind.Module },
		{ label = "shadow_to_opacity", kind = lspkind.Module },
		{ label = "vertex_lighting", kind = lspkind.Module },
		{ label = "particle_trails", kind = lspkind.Module },
		{ label = "alpha_to_coverage", kind = lspkind.Module },
		{ label = "alpha_to_coverage_and_one", kind = lspkind.Module },
		{ label = "fog_disabled", kind = lspkind.Module },
	},
	global = {
		{ label = "OUTPUT_IS_SRGB", kind = lspkind.Constant },
		{ label = "CLIP_SPACE_FAR", kind = lspkind.Constant },
	},
	vertex_in = {
		{ label = "VIEWPORT_SIZE", kind = lspkind.Constant },
		{ label = "VIEW_MATRIX", kind = lspkind.Constant },
		{ label = "INV_VIEW_MATRIX", kind = lspkind.Constant },
		{ label = "MAIN_CAM_INV_VIEW_MATRIX", kind = lspkind.Constant },
		{ label = "INV_PROJECTION_MATRIX", kind = lspkind.Constant },
		{ label = "NODE_POSITION_WORLD", kind = lspkind.Constant },
		{ label = "NODE_POSITION_VIEW", kind = lspkind.Constant },
		{ label = "CAMERA_POSITION_WORLD", kind = lspkind.Constant },
		{ label = "CAMERA_DIRECTION_WORLD", kind = lspkind.Constant },
		{ label = "CAMERA_VISIBLE_LAYERS", kind = lspkind.Constant },
		{ label = "INSTANCE_ID", kind = lspkind.Constant },
		{ label = "INSTANCE_CUSTOM", kind = lspkind.Constant },
		{ label = "VIEW_INDEX", kind = lspkind.Constant },
		{ label = "VIEW_MONO_LEFT", kind = lspkind.Constant },
		{ label = "VIEW_RIGHT", kind = lspkind.Constant },
		{ label = "EYE_OFFSET", kind = lspkind.Constant },
		{ label = "VERTEX_ID", kind = lspkind.Constant },
		{ label = "MODEL_MATRIX", kind = lspkind.Constant },
		{ label = "MODEL_NORMAL_MATRIX", kind = lspkind.Constant },
		{ label = "BONE_INDICES", kind = lspkind.Constant },
		{ label = "BONE_WEIGHTS", kind = lspkind.Constant },
		{ label = "CUSTOM0", kind = lspkind.Constant },
		{ label = "CUSTOM1", kind = lspkind.Constant },
		{ label = "CUSTOM2", kind = lspkind.Constant },
		{ label = "CUSTOM3", kind = lspkind.Constant },
	},
	vertex_inout = {
		{ label = "VERTEX", kind = lspkind.Property },
		{ label = "NORMAL", kind = lspkind.Property },
		{ label = "TANGENT", kind = lspkind.Property },
		{ label = "BINORMAL", kind = lspkind.Property },
		{ label = "UV", kind = lspkind.Property },
		{ label = "UV2", kind = lspkind.Property },
		{ label = "COLOR", kind = lspkind.Property },
		{ label = "POINT_SIZE", kind = lspkind.Property },
		{ label = "MODELVIEW_MATRIX", kind = lspkind.Property },
		{ label = "MODELVIEW_NORMAL_MARIX", kind = lspkind.Property },
		{ label = "PROJECTION_MATRIX", kind = lspkind.Property },
	},
	vertex_out = {
		{ label = "POSITION", kind = lspkind.Property },
		{ label = "ROUGHNESS", kind = lspkind.Property },
	},
	fragment_in = {
		{ label = "VIEWPORT_SIZE", kind = lspkind.Constant },
		{ label = "FRAGCOORD", kind = lspkind.Constant },
		{ label = "FRONT_FACING", kind = lspkind.Constant },
		{ label = "VIEW", kind = lspkind.Constant },
		{ label = "UV", kind = lspkind.Constant },
		{ label = "UV2", kind = lspkind.Constant },
		{ label = "COLOR", kind = lspkind.Constant },
		{ label = "POINT_COORD", kind = lspkind.Constant },
		{ label = "MODEL_MATRIX", kind = lspkind.Constant },
		{ label = "MODEL_NORMAL_MATRIX", kind = lspkind.Constant },
		{ label = "VIEW_MATRIX", kind = lspkind.Constant },
		{ label = "INV_VIEW_MATRIX", kind = lspkind.Constant },
		{ label = "PROJECTION_MATRIX", kind = lspkind.Constant },
		{ label = "INV_PROJECTION_MATRIX", kind = lspkind.Constant },
		{ label = "NODE_POSITION_WORLD", kind = lspkind.Constant },
		{ label = "NODE_POSITION_VIEW", kind = lspkind.Constant },
		{ label = "CAMERA_POSITION_WORLD", kind = lspkind.Constant },
		{ label = "CAMERA_DIRECTION_WORLD", kind = lspkind.Constant },
		{ label = "CAMERA_VISIBLE_LAYERS", kind = lspkind.Constant },
		{ label = "VERTEX", kind = lspkind.Constant },
		{ label = "VIEW_INDEX", kind = lspkind.Constant },
		{ label = "VIEW_MONO_LEFT", kind = lspkind.Constant },
		{ label = "VIEW_RIGHT", kind = lspkind.Constant },
		{ label = "EYE_OFFSET", kind = lspkind.Constant },
		{ label = "SCREEN_UV", kind = lspkind.Constant },
	},
	fragment_inout = {
		{ label = "LIGHT_VERTEX", kind = lspkind.Property },
		-- { label = "BLACKLIGHT", kind = lspkind.Property },
		{ label = "NORMAL", kind = lspkind.Property },
		{ label = "TANGENT", kind = lspkind.Property },
		{ label = "BINORMAL", kind = lspkind.Property },
	},
	fragment_out = {
		{ label = "DEPTH", kind = lspkind.Property },
		{ label = "NORMAL_MAP", kind = lspkind.Property },
		{ label = "NORMAL_MAP_DEPTH", kind = lspkind.Property },
		{ label = "ALBEDO", kind = lspkind.Property },
		{ label = "ALPHA", kind = lspkind.Property },
		{ label = "ALPHA_SCISSOR_THRESHOLD", kind = lspkind.Property },
		{ label = "ALPHA_HASH_SCALE", kind = lspkind.Property },
		{ label = "ALPHA_ANTIALIASING_EDGE", kind = lspkind.Property },
		{ label = "ALPHA_TEXTURE_COORDINATE", kind = lspkind.Property },
		{ label = "PREMULA_ALPHA_FACTOR", kind = lspkind.Property },
		{ label = "METALLIC", kind = lspkind.Property },
		{ label = "SPECULAR", kind = lspkind.Property },
		{ label = "ROUGHNESS", kind = lspkind.Property },
		{ label = "RIM", kind = lspkind.Property },
		{ label = "RIM_TINT", kind = lspkind.Property },
		{ label = "CLEARCOAT", kind = lspkind.Property },
		{ label = "CLEARCOAT_GLOSS", kind = lspkind.Property },
		{ label = "ANISOTROPY", kind = lspkind.Property },
		{ label = "ANISOTROPY_FLOW", kind = lspkind.Property },
		{ label = "SSS_STRENGTH", kind = lspkind.Property },
		{ label = "SSS_TRANSMITTANCE_COLOR", kind = lspkind.Property },
		{ label = "SSS_TRANSMITTANCE_DEPTH", kind = lspkind.Property },
		{ label = "SSS_TRANSMITTANCE_BOOST", kind = lspkind.Property },
		{ label = "AO", kind = lspkind.Property },
		{ label = "AO_LIGHT_AFFECT", kind = lspkind.Property },
		{ label = "EMISSION", kind = lspkind.Property },
		{ label = "FOG", kind = lspkind.Property },
		{ label = "RADIANCE", kind = lspkind.Property },
		{ label = "IRRADIANCE", kind = lspkind.Property },
	},

	light_in = {
		{ label = "VIEWPORT_SIZE", kind = lspkind.Constant },
		{ label = "FRAGCOORD", kind = lspkind.Constant },
		{ label = "MODEL_MATRIX", kind = lspkind.Constant },
		{ label = "INV_VIEW_MATRIX", kind = lspkind.Constant },
		{ label = "VIEW_MATRIX", kind = lspkind.Constant },
		{ label = "PROJECTION_MATRIX", kind = lspkind.Constant },
		{ label = "INV_PROJECTION_MATRIX", kind = lspkind.Constant },
		{ label = "NORMAL", kind = lspkind.Constant },
		{ label = "SCREEN_UV", kind = lspkind.Constant },
		{ label = "UV", kind = lspkind.Constant },
		{ label = "UV2", kind = lspkind.Constant },
		{ label = "VIEW", kind = lspkind.Constant },
		{ label = "LIGHT", kind = lspkind.Constant },
		{ label = "LIGHT_COLOR", kind = lspkind.Constant },
		{ label = "SPECULAR_AMOUNT", kind = lspkind.Constant },
		{ label = "LIGHT_IS_DIRECTIONAL", kind = lspkind.Constant },
		{ label = "ATTENUATION", kind = lspkind.Constant },
		{ label = "ALBEDO", kind = lspkind.Constant },
		{ label = "BACKLIGHT", kind = lspkind.Constant },
		{ label = "METALLIC", kind = lspkind.Constant },
		{ label = "ROUGHNESS", kind = lspkind.Constant },
	},
	light_out = {
		{ label = "DIFFUSE_LIGHT", kind = lspkind.Property },
		{ label = "SPECULAR_LIGHT", kind = lspkind.Property },
		{ label = "ALPHA", kind = lspkind.Property },
	},
}
