local lspkind = vim.lsp.protocol.CompletionItemKind

return {
  { label = "void",             kind = lspkind.Struct },
  { label = "bool",             kind = lspkind.Struct },
  { label = "bvec2",            kind = lspkind.Struct },
  { label = "bvec3",            kind = lspkind.Struct },
  { label = "bvec4",            kind = lspkind.Struct },
  { label = "int",              kind = lspkind.Struct },
  { label = "ivec2",            kind = lspkind.Struct },
  { label = "ivec3",            kind = lspkind.Struct },
  { label = "ivec4",            kind = lspkind.Struct },
  { label = "uint",             kind = lspkind.Struct },
  { label = "uvec2",            kind = lspkind.Struct },
  { label = "uvec3",            kind = lspkind.Struct },
  { label = "uvec4",            kind = lspkind.Struct },
  { label = "float",            kind = lspkind.Struct },
  { label = "vec2",             kind = lspkind.Struct },
  { label = "vec3",             kind = lspkind.Struct },
  { label = "vec4",             kind = lspkind.Struct },
  { label = "mat2",             kind = lspkind.Struct },
  { label = "mat3",             kind = lspkind.Struct },
  { label = "mat4",             kind = lspkind.Struct },
  { label = "sampler2D",        kind = lspkind.Struct },
  { label = "isampler2D",       kind = lspkind.Struct },
  { label = "usampler2D",       kind = lspkind.Struct },
  { label = "sampler2DArray",   kind = lspkind.Struct },
  { label = "isampler2DArray",  kind = lspkind.Struct },
  { label = "usampler2DArray",  kind = lspkind.Struct },
  { label = "sampler3D",        kind = lspkind.Struct },
  { label = "isampler3D",       kind = lspkind.Struct },
  { label = "usampler3D",       kind = lspkind.Struct },
  { label = "samplerCube",      kind = lspkind.Struct },
  { label = "samplerCubeArray", kind = lspkind.Struct },
}
